### ISSUE TITLE
program stops responding when analyzing large folder

### ISSUE THREAD

**Issue by ghost** [RouHim/disCoverJ#65]
program hangs up when analyzing large folder with subfolders
![Screenshot 2023-03-01 120410](https://user-images.githubusercontent.com/117180022/222121815-f37271ab-eaac-47f3-b56d-ad3c49ee9bdf.jpg)

**Comment by RouHim** [comment]
Can you please send me the log file?

**Comment by ghost** [comment]
it's empty

**Comment by RouHim** [comment]
On which operating system are you using it?

**Comment by ghost** [comment]
Win11 (22H2)

**Comment by RouHim** [comment]
Ok I'll see if I can reproduce it with a large number of files. Is it possible that the computer has little RAM?

**Comment by ghost** [comment]
32GB RAM, discoverJ is consuming 4440MB when stuck one file before the end.

**Comment by RouHim** [comment]
Ok I was able to reproduce this. Oof thats a lot of files tho :D I'll see how I can optimize this to get a smoother experience.
I'll keep this ticket open to track this issue.

**Comment by RouHim** [comment]
@rusty4174 I'm going to merge my fix this evening, would be awesome if you could test it the next days :)

**Comment by ghost** [comment]
working now - thanks for your support!

**Comment by RouHim** [comment]
Awesome, thanks for testing
